package com.example.analysis;

import java.io.IOException;
import java.util.*;

public class Main {
    public static void main(String[] args) {
        try {
            List<SalesRecord> salesRecords = SalesDataLoader.loadFromCsv("sales.csv");
            System.out.println("Total Revenue generated is: " + SalesAnalyzer.totalRevenue(salesRecords));
            System.out.println("Revenue generated By each Region is: " + SalesAnalyzer.revenueByRegion(salesRecords));
            System.out.println("Revenue generated By each Product is: " + SalesAnalyzer.revenueByProduct(salesRecords));
            System.out.println("Average Order Value is: " + SalesAnalyzer.averageOrderValue(salesRecords));
            SalesAnalyzer.bestProductByRevenue(salesRecords)
                    .ifPresent(entry ->
                            System.out.println("Best Product: " + entry.getKey() + " = " + entry.getValue())
                    );
            System.out.println("Revenue generated By each Month is: " + SalesAnalyzer.revenueByMonth(salesRecords));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
